name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH for deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy code to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.207.111.238 << 'EOF'
  # Ensure the directory exists
  if [ -d "/home/ubuntu/terraform" ]; then
    cd /home/ubuntu/terraform
  else
    echo "Directory /home/ubuntu/terraform not found!"
    exit 1
  fi

  # Perform git pull
  git pull origin main

  # Install dependencies
  npm install

  # Check if any PM2 processes are running
  if pm2 list | grep -q "No processes"; then
    # If no processes are found, start the app
    pm2 start index.js --name "my-app"  # Replace 'index.js' with your app's entry file
  else
    # Restart the app using pm2
    pm2 restart all
  fi
EOF

